all:
	./node_modules/.bin/babel js/content/jsx/content-script-jsx.js > js/content/public/content-script.js
	./node_modules/.bin/babel js/content/jsx/UrlItemButtons.react.js > js/content/public/UrlItemButtons.js
	./node_modules/.bin/babel js/content/jsx/UrlItemText.react.js > js/content/public/UrlItemText.js
	./node_modules/.bin/babel js/content/jsx/UrlItemUrlText.react.js > js/content/public/UrlItemUrlText.js